 const generateContent = (req, res) => {
    const { prompt } = req.body;

    if (!prompt) {
        return res.status(400).json({ error: 'Prompt is required' });
    }

    // Simulate AI response
    const generatedText = `This is a generated response for the prompt: "${prompt}". In a real application, this would be generated by an AI model.`;

    res.json({ response: generatedText });
};

module.exports = {
    generateContent,
};
